name: Testing with the private action

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Notion task handle actions
        uses: ./.github/actions/nau/
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
